"""Cross-layer public document contracts; generated bytes are synthetic only."""
import asyncio
import hashlib
import json
from pathlib import Path

import pytest
from mcp.shared.memory import create_connected_server_and_client_session

import knowledge as k
import server
from import_snapshot import import_snapshot


@pytest.mark.parametrize('native', [False, True])
@pytest.mark.parametrize('transport', ['direct', 'mcp'])
def test_maximum_imported_document_paginates_to_end(tmp_path, monkeypatch, native, transport):
    size = 2 * 1024 * 1024
    line = b'SYNTHETIC TEST FIXTURE, NOT DOCUMENTATION.\n'
    data = (line * (size // len(line) + 1))[:size]
    identifier = 'native-7' if native else 'hydro-7'
    captures = tmp_path / 'captures'
    captures.mkdir()
    (captures / (identifier + ('.txt' if native else '.md'))).write_bytes(data)
    source = dict(id=identifier, provider='native' if native else 'hydromancer',
                  section='native' if native else 'platform', title='Synthetic maximum',
                  url=('https://hyperliquid.gitbook.io/' if native else 'https://docs.hydromancer.xyz/') + 'synthetic-maximum',
                  sha256=hashlib.sha256(data).hexdigest(), snapshot_date='2026-01-01',
                  snapshot_date_basis='synthetic test fixture')
    catalog = tmp_path / 'catalog.json'
    catalog.write_text(json.dumps({'format_version': 1, 'sources': [source]}))
    output = tmp_path / 'snapshot'
    assert import_snapshot(catalog, captures, output) == 1
    monkeypatch.setattr(k, 'HYDRO', output / 'hydromancer')
    monkeypatch.setattr(k, 'NATIVE', output / 'native')
    db = tmp_path / 'maximum.sqlite'
    assert k.build_index(db)['source_count'] == 1
    monkeypatch.setattr(server, 'fetch', lambda id, offset=0: k.fetch(id, offset, db=db))

    async def paginate():
        async with create_connected_server_and_client_session(server.mcp) as session:
            offset, chunks = 0, []
            while offset is not None:
                if transport == 'mcp':
                    response = await session.call_tool('fetch_public_doc', {'id': identifier, 'offset': offset})
                    assert not response.isError, response
                    page = response.structuredContent or json.loads(response.content[0].text)
                else:
                    page = k.fetch(identifier, offset, db=db)
                assert page['offset'] == offset
                assert 0 < len(page['text']) <= 10000
                assert page['document_chars'] == size
                chunks.append(page['text'])
                next_offset = page['next_offset']
                assert next_offset is None or next_offset == offset + len(page['text'])
                offset = next_offset
            assert ''.join(chunks).encode('utf-8') == data
            if transport == 'mcp':
                tools = await session.list_tools()
                schema = next(t.inputSchema for t in tools.tools if t.name == 'fetch_public_doc')
                assert schema['properties']['offset']['maximum'] == size
                response = await session.call_tool('fetch_public_doc', {'id': identifier, 'offset': size + 1})
                assert response.isError
            else:
                with pytest.raises(ValueError, match='offset'):
                    k.fetch(identifier, size + 1, db=db)

    asyncio.run(paginate())


@pytest.mark.parametrize('native', [False, True])
def test_direct_ledger_oversize_rejected_before_build(tmp_path, synthetic_corpus, native):
    root = k.NATIVE if native else k.HYDRO
    ledger = root / ('source_records.json' if native else 'rest-a-assignment.json')
    rows = json.loads(ledger.read_text())
    record = rows[0]
    # Byte limit, not character limit (UTF-8); otherwise >2 MiB can slip through.
    data = ('é' * (1024 * 1024) + 'x').encode('utf-8')
    Path(record['file' if native else 'path']).write_bytes(data)
    record['sha256_text' if native else 'sha256'] = hashlib.sha256(data).hexdigest()
    ledger.write_text(json.dumps(rows))
    db = tmp_path / 'existing.sqlite'
    db.write_bytes(b'Existing index')
    before = set(tmp_path.iterdir())
    with pytest.raises(ValueError, match='exceeds 2 MiB'):
        k.build_index(db)
    assert db.read_bytes() == b'Existing index'
    assert set(tmp_path.iterdir()) == before


@pytest.mark.parametrize('native', [False, True])
@pytest.mark.parametrize('record_id', [10000, '00001', ' 1', '1\n', 1.0])
def test_direct_ledger_rejects_unfetchable_ids_without_replacing_index(
        tmp_path, synthetic_corpus, native, record_id):
    db = tmp_path / 'existing.sqlite'
    k.build_index(db)
    before = db.read_bytes()
    root = k.NATIVE if native else k.HYDRO
    ledger = root / ('source_records.json' if native else 'rest-a-assignment.json')
    rows = json.loads(ledger.read_text())
    rows[0]['id'] = record_id
    ledger.write_text(json.dumps(rows))
    with pytest.raises(ValueError, match='document ID'):
        k.build_index(db)
    assert db.read_bytes() == before
    assert not list(tmp_path.glob('*.building*'))
